name: Copy data FINDCovTrackerData repository

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 15 * * *"
    - cron: "0 16 * * *"
    - cron: "0 17 * * *"
    - cron: "0 18 * * *"
    - cron: "0 19 * * *"
    - cron: "0 20 * * *"
    - cron: "0 21 * * *"
    - cron: "0 22 * * *"
    - cron: "0 23 * * *"
    - cron: "0 24 * * *"
    - cron: "0 1 * * *"
    - cron: "0 2 * * *"

  jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: get data
        run: |
          curl https://raw.githubusercontent.com/finddx/FINDCov19TrackerData/master/processed/data_all.csv
      - name: Add data
        run: |
          git add data/data_all.csv
      - name: Commit data
        run: |
          git commit -m "data updated"
      - name: Push data
        uses: ad-m/github-push-action@master
        run: |
          git push origin main
