name: Copy data FINDCovTrackerData repository

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "10 5 * * *"
    - cron: "10 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: update data
          run: |
            git config --global user.name 'JuanVallarta'
            git config --global user.email 'vallartajuan@hotmail.com'
            cd data/ && { curl -O https://raw.githubusercontent.com/finddx/FINDCov19TrackerData/master/processed/data_all.csv; cd -; }
            git add data/data_all.csv
            git commit -m "data updated" || echo "Nothing to update"
            git push
